### ISSUE TITLE
ERROR! 'version' is not a valid attribute for a RoleMetadata

### ISSUE THREAD

**Issue by David-Gil** [newmen/ansible-rvm#9]
When using this role Ansible outputs this message:

---

ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to have been in '/etc/ansible/roles/altermn.rvm/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---

galaxy_info:
## ^ here

After removing the version line in the metadata file the role works ok.

I have looked up other roles and none of them have the version line.

Ansible version (development):
ansible-playbook 2.2.0 (devel aece03312f) last updated 2016/07/27 13:10:48 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/07/26 15:42:03 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/07/26 15:42:04 (GMT +200)
  config file = /home/david/devel/ansible/playbooks/ansible.cfg
  configured module search path = Default w/o overrides

**Comment by newmen** [comment]
Hi @David-Gil 
Thanks for your feedback. Can you please send your pull request to master branch of my repository?
And one more question... Why you does not use the official role from RVM team? This role is located here: https://github.com/rvm/rvm1-ansible

**Comment by nfedyashev** [comment]
@newmen 
@David-Gil 
[this PR](https://github.com/newmen/ansible-rvm/pull/10) fixes it

**Comment by newmen** [comment]
Thanks @nfedyashev
